### ISSUE TITLE
Failure during compiling

### ISSUE THREAD

**Issue by zurabi97** [android-linux-stable/tissot#2]
Trying to compile the tissot kernel and I get this:

drivers/media/platform/msm/camera_v2/isp/msm_b
uf_mgr.o net/ipv4/ah4.o
drivers/media/platform/msm/camera v2/isp/msmi
sp_util.o
In file included from drivers/media/platform/msm/camera
v2/isp/msm isp_util.c:24:0:
include/trace/events/msm_cam.h:19:21: fatal error: msmi
sp.h: No such file or directory
#include "msm_isp.h"

compilation terminated.
scripts/Makefile.build: 257: recipe for target drivers/m
edia/platform/msm/camera_v2/isp/msm_isp_util.o' failed
make[6]: [drivers/media/platform/msm/camera_v2/isp/m
sm_isp_util.o] Error 1
scripts/Makefile.build:402: recipe for target drivers/m
edia/platform/msm/camera_v2/isp' failed
make[5]: [drivers/media/platform/msm/camera_v2/isp]
Error 2
scripts/Makefile.build:402: recipe for target "drivers/m
edia/platform/msm/camera_v2' failed
make[4]: [drivers/media/platform/msm/camera_V2] Erro
r2
scripts/Makefile.build:402: recipe for target drivers/m
edia/platform/msm' failed
make[31: [drivers/media/platform/msm] Error 2
scripts/Makefile.build:402: recipe for target "drivers/m
edia/platform' failed
make[2]: [drivers/media/platform] Error 2,
scripts/Makefile.build:402: recipe for target "drivers/m
edia' failed
make[1]: [drivers/media] Error 2
Makefile:965: recipe for target "drivers' failed
make: [drivers] Error 2
сс net/ipv4/esp4.o
make: Waiting for unfinished jobs....

Maybe is something missing in the kernel tree of tissot?

**Comment by nathanchance** [comment]
No, you need to use `O=out` on all of your make invocations.

`make tissot-perf_defconfig` becomes `make O=out tissot-perf_defconfig` and so on and so forth.
